# version: "3.8"

# services:
#   django:
#     image: django-docker
#     build: .
#     ports:
#       - "8001:8001"


version: "3"

services:
    web:
      build: .
      command: python manage.py runserver 0.0.0.0:8000
      ports:
      - 8000:8000